"""Build exports and readable catalogs from canonical JSON. --check never writes."""
from __future__ import annotations

import argparse
import collections
import csv
import hashlib
import html
import io
import json
import re
import sys

from common import CSV_FIELDS, DIMENSIONS, ROOT, check_source, flat_row, json_text, load_programs, read_json, source_urls

REPO_URL = "https://github.com/luc3xhj/startup-accelerators"
VERSION = "0.1.0"
TYPE_ZH = {
    "Accelerator": "加速器", "Incubator": "孵化器", "Residency": "驻留项目",
    "Fellowship": "Fellowship", "Corporate / market access": "企业合作与市场拓展",
    "Community / education": "社群与创业教育",
}
GROUPS = {
    "Overview": ["Program", "Network", "Program Type", "Primary Value", "Region", "Location", "Focus", "Stage", "Duration"],
    "Funding & economic terms": ["Capital Type", "Guaranteed Capital", "Funding / Support", "Funding Trigger", "Non-dilutive", "Equity / Economic Terms", "Capital Disclosure Status", "Capital Terms Confidence"],
    "Eligibility": ["Company Required at Application", "Geography / Affiliation Restriction", "Can Apply Pre-Idea", "Can Apply Solo", "Official / Must-Have Requirements", "Strong-to-Have", "Eligibility Disclosure Status", "Eligibility Confidence"],
    "Attendance & international founders": ["Format", "On-site Required", "On-site / Attendance", "International Founder", "Visa Support Level", "Visa / Relocation"],
    "Applications & public contacts": ["Application Status", "Deadline / Next Intake", "Application Materials", "Application Link", "Website", "Public Contact Name", "Public Contact Role", "Public Email", "Public Contact Route"],
    "Sources & verification": ["Research Confidence", "Last Verified", "Primary Source", "Verification"],
    "Foundshore editorial assessment": ["Foundshore Score", "Foundshore Tier", "Foundshore Verdict", "Foundshore Best Fit", "Foundshore Not Fit", "Notes"],
}


def md(value, limit=None):
    if value is None or value == "":
        return "—"
    text = str(value).strip()
    if limit and len(text) > limit:
        text = text[:limit - 1].rstrip() + "…"
    text = html.escape(text, quote=False).replace("|", "&#124;")
    text = re.sub(r"([\\`*\[\]])", r"\\\1", text)
    return text.replace("\n", "<br>")


def link(label, url):
    return f"[{md(label)}](<{url}>)"


def table(headers, rows):
    return "| " + " | ".join(headers) + " |\n| " + " | ".join("---" for _ in headers) + " |\n" + "".join("| " + " | ".join(row) + " |\n" for row in rows)


def csv_text(programs):
    output = io.StringIO(newline="")
    writer = csv.DictWriter(output, fieldnames=CSV_FIELDS, lineterminator="\n")
    writer.writeheader()
    writer.writerows(flat_row(program) for program in programs)
    return output.getvalue()


def stats_block(programs, taxonomy, zh=False):
    networks = len({p["network_en"] for p in programs})
    dates = sorted({p["facts"]["Last Verified"] for p in programs})
    date_span = dates[0] if len(dates) == 1 else f"{dates[0]} – {dates[-1]}"
    if zh:
        summary = f"**{len(programs)} 个项目 · {networks} 个项目网络 · {len(taxonomy['type'])} 类项目 · {len(taxonomy['region'])} 个地区标签**\n\n数据中记录的核验日期：**{date_span}**。申请状态与条款是研究快照，申请前请查看官方页面。\n\n"
        headers = ["项目类型", "数量"]
    else:
        summary = f"**{len(programs)} programs · {networks} networks · {len(taxonomy['type'])} program types · {len(taxonomy['region'])} region tags**\n\nSource-recorded verification dates: **{date_span}**. Application status and terms are a research snapshot; check official pages before applying.\n\n"
        headers = ["Program type", "Entries"]
    counts = collections.Counter(tag for p in programs for tag in p["categories"]["type"])
    rows = [[TYPE_ZH.get(kind, kind) if zh else kind, str(counts[kind])] for kind in taxonomy["type"]]
    return summary + table(headers, rows)


def catalog(programs, taxonomy, zh=False):
    title = "加速器与创业者项目目录" if zh else "Accelerator & founder program directory"
    intro = "按项目类型分组，每组按英文名称排序。地区标签可以重叠；评分不参与默认排序。" if zh else "Grouped by program type, alphabetized by English name. Region tags overlap; editorial scores do not determine listing order."
    notice = "以下资金与申请信息反映条目中的研究日期，不代表当前正在招生。完整条目保留来源与条款。" if zh else "Funding and application information reflects each record's research date, not current enrollment. Open a profile for full terms and sources."
    lines = [f"# {title}", "", "<!-- Generated by scripts/build.py. Edit data/programs/*.json instead. -->", "", f"[README](README.zh-CN.md) · [English](DIRECTORY.md)" if zh else "[README](README.md) · [中文](DIRECTORY.zh-CN.md)", "", intro, "", notice, "", f"**{len(programs)} {'个项目' if zh else 'programs'}**", ""]
    for kind in taxonomy["type"]:
        matches = [p for p in programs if kind in p["categories"]["type"]]
        lines.extend([f"## {TYPE_ZH.get(kind, kind) if zh else kind}", "", f"**{len(matches)} {'个项目' if zh else 'programs'}**", ""])
        headers = ["项目", "地区 / 地点", "资金 / 支持", "参与方式", "核验日期"] if zh else ["Program", "Region / location", "Funding / support", "Attendance", "Last verified"]
        rows = []
        for program in matches:
            facts = program.get("facts_raw", {}) if zh else program["facts"]
            def value(field):
                return facts.get(field, program["facts"].get(field))
            region = ", ".join(program["categories"]["region"])
            rows.append([link(program["name"] if zh else program["name_en"], f"docs/programs/{program['id']}.md"), md(region) + "<br>" + md(value("Location")), md(value("Funding / Support"), 140), md(", ".join(program["categories"]["attendance"])), md(program["facts"]["Last Verified"])])
        lines.extend([table(headers, rows), ""])
    return "\n".join(lines).rstrip() + "\n"


def fact_value(program, field, value):
    if field == "Primary Source":
        return "<br>".join(link(url, url) for url in source_urls(program))
    if field in {"Website", "Application Link"}:
        return link(value, value)
    return md(value)


def profile(program):
    facts = program["facts"]
    lines = [f"# {md(program['name_en'])}", "", "<!-- Generated by scripts/build.py. Edit the canonical JSON record. -->", "", f"[Directory](../../DIRECTORY.md) · [中文目录](../../DIRECTORY.zh-CN.md) · [Edit / raw JSON](../../data/programs/{program['id']}.json)", "", f"**{md(program['network_en'])}** · {md(', '.join(program['categories']['type']))}", "", f"Recorded verification date: **{md(facts['Last Verified'])}**. These are snapshot values, not a live application-status feed.", ""]
    included = set()
    for group, fields in GROUPS.items():
        present = [field for field in fields if field in facts]
        if not present:
            continue
        included.update(present)
        lines.extend([f"## {group}", ""])
        if group == "Foundshore editorial assessment":
            lines.extend(["The imported assessment is Foundshore's editorial opinion. The source does not include a complete scoring formula; the repository does not recalculate or present it as an objective ranking.", ""])
        lines.extend([table(["Field", "Recorded value"], [[md(field), fact_value(program, field, facts[field])] for field in present]), ""])
    remaining = sorted(set(facts) - included)
    if remaining:
        lines.extend(["## Other recorded facts", "", table(["Field", "Recorded value"], [[md(field), md(facts[field])] for field in remaining]), ""])
    if program.get("ranking"):
        lines.extend(["## Imported ranking metadata", "", "Amounts retain their source currency and basis. Conditional funding, ceilings and credits must not be treated as guaranteed cash.", "", table(["Field", "Recorded value"], [[md(field), md(value)] for field, value in program["ranking"].items()]), ""])
    if program.get("facts_raw"):
        lines.extend(["<details>", "<summary>原始字段 / original-language facts</summary>", "", table(["字段 / field", "原始内容 / original value"], [[md(field), md(value)] for field, value in program["facts_raw"].items()]), "", "</details>", ""])
    return "\n".join(lines).rstrip() + "\n"


def quality_report(programs, origin):
    dates = collections.Counter(p["facts"]["Last Verified"] for p in programs)
    missing_stage = [p for p in programs if not p["categories"]["stage"]]
    multiple_sources = [p for p in programs if len(source_urls(p)) > 1]
    count_amount = sum(p.get("ranking", {}).get("amount") is not None for p in programs)
    lines = ["# Data quality report", "", "<!-- Generated by scripts/build.py; structural checks do not re-verify external facts. -->", "", f"{len(programs)} canonical records, all passing the program schema, unique-ID checks, taxonomy checks and source-URL syntax validation.", "", "## Coverage", "", table(["Measure", "Count"], [["Program records", str(len(programs))], ["Records with website, application link, source and verification date", str(len(programs))], ["Records with multiple primary-source links", str(len(multiple_sources))], ["Records with a numeric reported funding amount", str(count_amount)], ["Records without a numeric reported funding amount", str(len(programs) - count_amount)], ["Records without a normalized stage tag", str(len(missing_stage))]]), "", "## Source-recorded verification dates", "", table(["Date", "Records"], [[date, str(count)] for date, count in sorted(dates.items())]), "", "These dates were supplied by the original research. Repository import and CI are not new factual verification events.", "", "## Unclassified stage tags", ""]
    if missing_stage:
        lines.extend(["The original classification is retained; no stage is invented to fill a gap.", "", *[f"- {link(p['name_en'], 'programs/' + p['id'] + '.md')}: recorded stage text is `{p['facts'].get('Stage', 'Not recorded')}`." for p in missing_stage], ""])
    else:
        lines.extend(["All records have a normalized stage tag.", ""])
    lines.extend(["## Provenance & assets", "", f"Original archive: {origin['program_count']} program records and {origin['record_count'] - origin['program_count']} metadata records. Its byte-for-byte SHA-256 is recorded in [provenance.json](../data/source/provenance.json).", "", "Logo paths, source URLs and layout metadata are preserved. The referenced `/program-logos/` image files were not included in the JSONL and are not bundled or displayed by this repository.", "", "English facts and original-language facts are retained separately. Empty values remain null; unknown funding amounts are not converted to zero.", "", "## Limits of these checks", "", "CI validates structure and reproducible exports. It does not visit the 150 program websites, confirm deadlines, infer visa commitments, or update editorial opinions. Corrections need source evidence and a genuine verification date.", ""])
    return "\n".join(lines)


def package(programs, origin):
    numeric = {"editorial_score": "integer", "reported_amount": "number"}
    return {
        "$schema": "https://datapackage.org/profiles/2.0/datapackage.json",
        "name": "startup-accelerators", "title": "Startup Accelerators & Founder Programs",
        "description": "A source-linked directory of accelerators, incubators, residencies, fellowships and founder support programs.",
        "version": VERSION, "homepage": REPO_URL,
        "licenses": [{"name": "CC-BY-4.0", "path": "https://creativecommons.org/licenses/by/4.0/", "title": "Creative Commons Attribution 4.0 International"}],
        "contributors": [{"title": "Lucas Jin (luc3xhj)", "role": "author", "path": "https://github.com/luc3xhj"}, {"title": "Foundshore", "role": "publisher", "path": "https://foundshore.com"}],
        "sources": [{"title": origin["original_manifest"]["source"], "path": "data/source/accelerators-complete.jsonl"}],
        "resources": [
            {"name": "programs-csv", "type": "table", "path": "data/accelerators.csv", "format": "csv", "mediatype": "text/csv", "encoding": "utf-8", "schema": {"fields": [{"name": field, "type": numeric.get(field, "string")} for field in CSV_FIELDS], "primaryKey": "id"}},
            {"name": "programs-json", "path": "data/accelerators.json", "format": "json", "mediatype": "application/json", "encoding": "utf-8"},
            {"name": "programs-jsonl", "path": "data/accelerators.jsonl", "format": "jsonl", "mediatype": "application/x-ndjson", "encoding": "utf-8"},
        ],
    }


def generate(root=ROOT):
    programs = load_programs(root)
    origin = check_source(root)
    taxonomy = read_json(root / "data/taxonomy.json")
    output = {
        "data/accelerators.json": json_text(programs),
        "data/accelerators.jsonl": "".join(json.dumps(p, ensure_ascii=False, separators=(",", ":"), allow_nan=False) + "\n" for p in programs),
        "data/accelerators.csv": csv_text(programs),
        "DIRECTORY.md": catalog(programs, taxonomy),
        "DIRECTORY.zh-CN.md": catalog(programs, taxonomy, zh=True),
        "docs/quality-report.md": quality_report(programs, origin),
        "datapackage.json": json_text(package(programs, origin)),
    }
    for program in programs:
        output[f"docs/programs/{program['id']}.md"] = profile(program)
    manifest = {"schema_version": "1.0.0", "dataset_version": VERSION, "program_count": len(programs), "network_count": len({p["network_en"] for p in programs}), "verification_dates": sorted({p["facts"]["Last Verified"] for p in programs}), "category_counts": {dimension: dict(sorted(collections.Counter(tag for p in programs for tag in p["categories"][dimension]).items())) for dimension in DIMENSIONS}, "original_archive_sha256": origin["jsonl_sha256"]}
    output["data/manifest.json"] = json_text(manifest)
    for name, zh in [("README.md", False), ("README.zh-CN.md", True)]:
        text = (root / name).read_text(encoding="utf-8")
        pattern = r"(?s)(<!-- STATS:start -->\n).*?(<!-- STATS:end -->)"
        updated, count = re.subn(pattern, lambda m: m[1] + stats_block(programs, taxonomy, zh) + "\n" + m[2], text)
        if count != 1:
            raise ValueError(f"{name}: expected exactly one stats block")
        output[name] = updated
    checksummed = sorted(name for name in output if name.startswith("data/accelerators.")) + ["data/source/accelerators-complete.jsonl"]
    output["SHA256SUMS"] = "".join(f"{hashlib.sha256(output[name].encode('utf-8')).hexdigest() if name in output else origin['jsonl_sha256']}  {name}\n" for name in checksummed)
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when generated files are out of date; do not modify files")
    args = parser.parse_args()
    try:
        output = generate()
    except (ValueError, OSError) as error:
        print(error, file=sys.stderr)
        return 1
    stale = []
    expected_profiles = {name for name in output if name.startswith("docs/programs/")}
    for old in (ROOT / "docs/programs").glob("*.md"):
        name = old.relative_to(ROOT).as_posix()
        if name not in expected_profiles:
            if args.check:
                stale.append(name)
            else:
                old.unlink()  # Remove only obsolete generated profiles, never canonical records.
    for name, text in output.items():
        path = ROOT / name
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                stale.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="")
    if stale:
        print("Generated files are stale; run python3 scripts/build.py:\n" + "\n".join(stale), file=sys.stderr)
        return 1
    print(f"OK: {len(output)} generated files {'are current' if args.check else 'written'}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
